/*
 * Copyright (C) 2017 Gaurav Vaidya <gaurav@ggvaidya.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.ggvaidya.scinames.model.change;

import java.util.Map;
import java.util.stream.Stream;

import com.ggvaidya.scinames.model.Project;

/**
 * A ChangeGenerator produces changes based on a project.
 * 
 * @author Gaurav Vaidya <gaurav@ggvaidya.com>
 */
public interface ChangeGenerator {
	/** Return a stream of potential changes generated by this project. */
	public Stream<PotentialChange> generate(Project project);
}